### ISSUE TITLE
ruboty-cronでチャンネルガチャを流した際にいきなりガチャ本体が流れる

### ISSUE THREAD

**Issue by sanfrecce-osaka** [pocke/ruboty-ruby-jp#27]
チャンネルガチャを `ruboty-cron` で流すようになりましたが、 `ruboty-cron` は実行コマンドを流さないで唐突にチャンネルガチャ本体のメッセージが流れてくるので新規のユーザーにはこれが何なのか少し分かりづらい気もするんですがどうでしょう？

[![Image from Gyazo](https://i.gyazo.com/bab17445b349bce91236d061d48da8eb.png)](https://gyazo.com/bab17445b349bce91236d061d48da8eb)

**Comment by sanfrecce-osaka** [comment]
`ruboty-cron` で使用する際は↓みたいな出力でどうでしょう？

```
さーて今回のチャンネルガチャは〜？
チャンネル名: #channel_name
トピック: 未設定
説明: 未設定
```

**Comment by pocke** [comment]
そうですね、何らかの説明があると親切そうです。
日次でやっていることがわかりやすいように「今日のチャンネル」みたいな言葉があったほうが良いかなあと思いました
